In [1]:
import uproot, awkward
from coffea.analysis_objects import JaggedCandidateArray
import numpy as np

In [2]:
file = uproot.open("root://cmseos.fnal.gov//eos/uscms/store/group/lpcmetx/SIDM/ffNtupleV2/2018/CRAB_PrivateMC/SIDM_BsTo2DpTo4Mu_MBs-1000_MDp-0p25_ctau-1p875/200129_122813/ffNtuple_0.root")

In [3]:
file.keys()

[b'ffNtuplizer;1', b'ffNtupleStat;1']

In [4]:
df=file['ffNtuplizer/ffNtuple']
nmu = df.array('muon_n')
print(nmu)
muon_x = df.array('muon_p4.fCoordinates.fX')
print(type(nmu))
print(type(muon_x))

[ 6  5 11 16  7 14 13  8  6 12  2 10 10  9  7  9 10 14  5  4 10 10 20  3
  7  6 13  2  8  7  9  8  5  6  6  4  7 13  8  4  6 12 10  9  6  8  6  6
  3  3  8  6  7  8 11 10 11 15 15  3  6  7  9  6 10  8  9  2 11  4  5  6
 15 14  8  8 13  8  5  7 10 17  4 12  3 12  5  9  4  5 10  3  5 16  6  6
 10  4  5  7  4  6  6 15  6 13  5  6 15 10 14  5  4  6  5  5 11  5  8  9
  8  7  5 11  6  8  6 19  3 15  6  7  9 15 15  7  5  9  6  9  5 12  3  6
  8  8 16  5  9  6 15  7  4  6 13  8 15 10  8 15 12  7 11  4 11  6  4  6
  7  9  8  7  9  8  9 22  4 10 19  4 12 10  3  4  5 14  8  5 15  8  7 12
  4  8  5  9 12  9  9  5  5  5  9  7 10  9  8 13 12  3  7  9  9  9 14  5
 10  7  7  8 10 10  6  4 10  4  9  7  5  9  6  6  5  8  6 12  7 12  9  6
  9  5  9 12  7 19  4  6 10  6 20  6  5  7  5  7  7  5  6 10  6  4  4 11
 11  7 11 11  6  6  6  9  5  6  7  5 10  6  4  4  5  5  3 12  5  7 10 16
  7  9  8 15 11 18  6  6 11 11 10  8  6  5 10  6 14  4  5  6 14  9  7  4
  4  6 10  8  7 11 11  7  3 10  7  8  8 10  7 10  8

In [4]:
#df.keys()

In [22]:
print(df.array('pfjet_pfcands_minTwoTkDist'))
print(df.array('pfjet_pfcand_charge'))
print(df.array('pfjet_pfcand_tkD0Min'))
d0 = df.array('pfjet_pfcand_tkD0Min')
print(np.isnan(np.sum(d0.flatten())))
print(d0.flatten()[:12])
#print(df.array('pfjet_n'))
#print((d0.flatten() > 0.01)[:12])
print(d0[:12])
#print((d0<0.001)[:12])
# NAN< or NAN > X is always false
# In Weinan's code, he sets nans to -1 for DCA 
print("------")
print(((d0*10000))[:12])
print((d0>0.01)[:12])
print(np.nan_to_num(d0.content, nan=-1)[:14])
print(d0.content[:14])
array = np.fmax(0, d0)
print(array[:12])
np.isnan(d0[:12])


[[0.049871378] [0.0065526813] [7.986847] ... [0.010394603] [0.0003027916] [0.032124534]]
[[[1, -1]] [[-1, 1]] [[-1, 1]] ... [[1, -1]] [[1, -1]] [[1, -1]]]
[[0.29765102] [0.0016054212] [0.040519454] ... [0.0011742662] [0.0010298681] [0.00037293957]]
True
[2.9765102e-01 1.6054212e-03 4.0519454e-02 3.4723982e-01 1.1853067e-03
 3.9836457e-03 2.1174878e-03 1.8134168e-03 8.4429054e-04 7.1686908e-04
 7.2665918e-01           nan]
[[0.29765102] [0.0016054212] [0.040519454] ... [0.7266592] [nan] [0.0035637517]]
------
[[2976.5103] [16.054213] [405.19455] ... [7266.592] [nan] [35.637516]]
[[True] [False] [True] ... [True] [False] [False]]
[ 2.9765102e-01  1.6054212e-03  4.0519454e-02  3.4723982e-01
  1.1853067e-03  3.9836457e-03  2.1174878e-03  1.8134168e-03
  8.4429054e-04  7.1686908e-04  7.2665918e-01 -1.0000000e+00
  3.5637517e-03  9.1621736e-03]
[2.9765102e-01 1.6054212e-03 4.0519454e-02 3.4723982e-01 1.1853067e-03
 3.9836457e-03 2.1174878e-03 1.8134168e-03 8.4429054e-04 7.1686908e-04
 7.2665

<JaggedArray [[False] [False] [False] ... [False] [True] [False]] at 0x7f9b4fd01f10>

In [6]:
charge = awkward.fromiter(df.array('pfjet_pfcand_charge'))
candtype = awkward.fromiter(df.array('pfjet_pfcand_type'))
print(charge)
print(charge.sum())
print(candtype)
print(charge[(candtype==3) | (candtype ==8)])
print(charge[(candtype==3) | (candtype ==8)].sum())

[[[1 -1]] [[-1 1]] [[-1 1]] ... [[1 -1]] [[1 -1]] [[1 -1]]]
[[0] [0] [0] ... [0] [0] [0]]
[[[8 8]] [[3 3]] [[3 3]] ... [[3 3]] [[3 3]] [[3 3]]]
[[[1 -1]] [[-1 1]] [[-1 1]] ... [[1 -1]] [[1 -1]] [[1 -1]]]
[[0] [0] [0] ... [0] [0] [0]]


In [34]:

dsaId = awkward.fromiter(df.array('pfjet_pfcand_dsamuonIdx')) #,dtype=np.int64)
print(dsaId)
print(dsaId.flatten(axis=1).layout)
dR = df.array('dsamuon_deltaRCosmicDSA')
print(type(dR))
print(dR)
#print(dR[:,3:4])
counts = dsaId.counts
#print(dsaId.flatten(axis=0).shape)
#print(dsaId.flatten(axis=1).shape)
#print(dsaId.flatten().shape)
#print(dsaId.offsets)

print(type(dR[dsaId.flatten(axis=1)]))
print(dR[dsaId.flatten(axis=1)])

dRs = awkward.JaggedArray.fromcounts(dsaId.flatten(axis=0).counts, dR[dsaId.flatten(axis=1)].flatten())
dR2s = awkward.JaggedArray.fromcounts(dsaId.counts, dRs)
print(dRs)
print(dR2s)

[[[2 1]] [[]] [[]] ... [[]] [[]] [[]]]
 layout 
[    ()] JaggedArray(starts=layout[0], stops=layout[1], content=layout[2])
[     0]   ndarray(shape=790, dtype=dtype('int64'))
[     1]   ndarray(shape=790, dtype=dtype('int64'))
[     2]   ndarray(shape=517, dtype=dtype('uint32'))
<class 'awkward.array.jagged.JaggedArray'>
[[1.8663409 1.8663409 1.8676202] [999.0 0.41905144 0.42356676 0.41905144] [999.0 0.3318739 0.342823 0.3318739 0.3481255 1.272743] ... [2.6946197 0.20622681 0.20622681 0.5524713] [2.1921937 999.0 2.1942294 2.1921937] [0.81220275 999.0 1.4117714 ... 0.8073964 1.0404793 0.69262624]]
<class 'awkward.array.jagged.JaggedArray'>
[[1.8676202 1.8663409] [] [] ... [] [] []]
[[1.8676202 1.8663409] [] [] ... [] [] []]
[[[1.8676202 1.8663409]] [[]] [[]] ... [[]] [[]] [[]]]


In [27]:
dsaId.flatten(axis=1).layout

 layout 
[    ()] JaggedArray(starts=layout[0], stops=layout[1], content=layout[2])
[     0]   ndarray(shape=790, dtype=dtype('int64'))
[     1]   ndarray(shape=790, dtype=dtype('int64'))
[     2]   ndarray(shape=517, dtype=dtype('uint32'))

In [26]:
myarray =  awkward.JaggedArray.fromiter([[1.1, 2.2, 3.3], [4.4, 5.5]]) #dsa muons per event, minimum dR
myarray2 = awkward.JaggedArray.fromiter([[[2,0], []], [[1,1]]]) #index of dsa muons per lepton jet per event
myarray3 = awkward.JaggedArray.fromiter([[2,0],[1,1]])

print(myarray2.flatten(axis=1))
print(myarray2.counts) #Number of lepton jets per event
print(myarray2.flatten(axis=0).counts) #Number of dsa muons per lepton jet
#print(myarray[myarray3])
#print(myarray[myarray2.flatten(axis=1)])

dRs = myarray[myarray2.flatten(axis=1)]
print(dRs.flatten())
step1 = awkward.JaggedArray.fromcounts(myarray2.flatten(axis=0).counts,dRs.flatten())
step2 = awkward.JaggedArray.fromcounts(myarray2.counts, step1)
print(dRs)
print(step1)
print(step2)
print(step2.min())

[[2 0] [1 1]]
[2 1]
[2 0 2]
[3.3 1.1 5.5 5.5]
[[3.3 1.1] [5.5 5.5]]
[[3.3 1.1] [] [5.5 5.5]]
[[[3.3 1.1] []] [[5.5 5.5]]]
[[1.1 inf] [5.5]]


In [84]:
muons = JaggedCandidateArray.candidatesfromcounts(
            df.array('muon_n'),
            px=df.array('muon_p4.fCoordinates.fX').flatten(),
            py=df.array('muon_p4.fCoordinates.fY').flatten(),
            pz=df.array('muon_p4.fCoordinates.fZ').flatten(),
            energy=df.array('muon_p4.fCoordinates.fT').flatten()
        )
      

In [81]:
muons2 =JaggedCandidateArray.candidatesfromcounts(
            df.array('muon_n'),
            px=df.array('muon_p4.fCoordinates.fX').flatten(),
            py=df.array('muon_p4.fCoordinates.fY').flatten(),
            pz=df.array('muon_p4.fCoordinates.fZ').flatten(),
            energy=df.array('muon_p4.fCoordinates.fT').flatten()
        )

In [74]:
print(df.array('muon_n').shape)

(33482,)


In [75]:
print(df.array('muon_p4.fCoordinates.fX').shape)

(33482,)


In [78]:
print(df.array('muon_p4.fCoordinates.fX').content)

[ 0.6730363   5.7934604  -0.98036504 ...  7.820814    5.016974
 -0.29913393]


In [85]:
print(muons.argmatch(muons2))

[[0 1 2 3 4 5] [0 1 2 3] [0 1 2 ... 4 5 6] ... [0] [0 1] [0 1 2]]


In [86]:
muons['match'] = (muons.argmatch(muons2))

In [89]:
print(muons['match']>=1)

[[False True True True True True] [False True True True] [False True True ... True True True] ... [False] [False True] [False True True]]


In [90]:
        RtriggerIso24Objs = JaggedCandidateArray.candidatesfromcounts(
            df.array('TOHLT_IsoMu24'),
            px=df.array('TOHLT_IsoMu24.fCoordinates.fX').flatten(),
            py=df.array('TOHLT_IsoMu24.fCoordinates.fY').flatten(),
            pz=df.array('TOHLT_IsoMu24.fCoordinates.fZ').flatten(),
            energy=df.array('TOHLT_IsoMu24.fCoordinates.fT').flatten(),
        ) 

In [91]:
print(muons.argmatch(RtriggerIso24Objs))

[[0 0 0 0 0 0] [0 0 0 0] [0 0 0 ... 0 0 0] ... [0] [0 0] [0 0 0]]


In [92]:
muons3 =JaggedCandidateArray.candidatesfromcounts(
            df.array('muon_n'),
            px=-1.0*df.array('muon_p4.fCoordinates.fX').flatten(),
            py=df.array('muon_p4.fCoordinates.fY').flatten(),
            pz=df.array('muon_p4.fCoordinates.fZ').flatten(),
            energy=df.array('muon_p4.fCoordinates.fT').flatten()
        )

In [95]:
print(muons.argmatch(muons3))

[[0 0 2 2 5 5] [3 3 2 0] [3 5 2 ... 6 1 4] ... [0] [1 1] [0 0 2]]


In [108]:
print(muons.counts)
print(RtriggerIso24Objs.counts)

[6 4 7 ... 1 2 3]
[1 1 1 ... 1 1 1]


In [106]:
combs = muons.p4.cross(RtriggerIso24Objs.p4, nested=True)
print(combs.i0.delta_r(combs.i1))

[[[0.097676866] [0.00018753819] [4.1931195] [4.202071] [3.7591202] [4.222533]] [[0.00024779816] [0.061374024] [2.5391037] [3.1416085]] [[3.9039602] [0.00011216777] [1.3543528] ... [1.8868182] [2.123903] [1.142219]] ... [[6.9996895e-05]] [[0.00015605858] [0.3269674]] [[6.129317e-05] [0.09311255] [2.4999914]]]


In [107]:
print((combs.i0.delta_r(combs.i1)<0.4).sum())

[[1 1 0 0 0 0] [1 1 0 0] [0 1 0 ... 0 0 0] ... [1] [1 1] [1 1 0]]


In [110]:
muons['testmatch'] = (combs.i0.delta_r(combs.i1)<0.4).sum()
muons

In [111]:
print(muons['testmatch'])

[[1 1 0 0 0 0] [1 1 0 0] [0 1 0 ... 0 0 0] ... [1] [1 1] [1 1 0]]


In [113]:
print(muons.testmatch)

[[1 1 0 0 0 0] [1 1 0 0] [0 1 0 ... 0 0 0] ... [1] [1 1] [1 1 0]]


In [114]:
print(muons.pt)

[[4.402158 27.710659 1.0565617 1.7638636 1.5527713 1.0370928] [26.309835 4.548486 1.3486903 1.6055921] [1.5987972 47.119114 1.1163747 ... 1.5879335 1.1754937 2.3379376] ... [31.243773] [39.734234 0.9361439] [25.16329 14.312583 0.88143235]]


In [115]:
muon_pairs = muons.distincts()
denominator_mask = ((muon_pairs.i0.pt > 30) & (abs(muon_pairs.i0.eta) < 2.4) & (muon_pairs.i0.testmatch))

In [136]:
muon_mask = (muons.pt > 30) & (abs(muons.eta) < 2.4) & (muons.testmatch)

In [121]:
print(denominator_mask.offsets)

[     0     15     21 ... 251457 251458 251461]


In [137]:
print(muon_pairs.i1[muon_mask.distincts().i1])

IndexError: jagged array used as index contains out-of-bounds values

In [141]:
muon_mask.distincts().i1.offsets

array([     0,     15,     21, ..., 251457, 251458, 251461])

In [135]:
muon_pairs.offsets

array([     0,     15,     21, ..., 251457, 251458, 251461])

In [143]:
tags=muon_pairs.i1

In [144]:
print(tags.pt.flatten())

[27.710659    1.0565617   1.7638636  ... 14.312583    0.88143235
  0.88143235]


In [145]:
tags.offsets

array([     0,     15,     21, ..., 251457, 251458, 251461])

In [146]:
tags[denominator_mask]

IndexError: jagged array used as index contains out-of-bounds values

In [147]:
denominator_mask

<JaggedArray [[0 0 0 ... 0 0 0] [0 0 0 0 0 0] [0 0 0 ... 0 0 0] ... [] [1] [0 0 0]] at 0x7f21379e8280>

In [148]:
tags

<JaggedArrayMethods [[<Row 1> <Row 2> <Row 3> ... <Row 4> <Row 5> <Row 5>] [<Row 7> <Row 8> <Row 9> <Row 8> <Row 9> <Row 9>] [<Row 11> <Row 12> <Row 13> ... <Row 15> <Row 16> <Row 16>] ... [] [<Row 128382>] [<Row 128384> <Row 128385> <Row 128385>]] at 0x7f21379fea30>

In [157]:
muon_pairs[((muon_pairs.i1.pt >30) & (abs(muon_pairs.i0.eta) < 2.4))]

<JaggedArrayMethods [[] [] [] ... [] [] []] at 0x7f21379feac0>

In [155]:
muon_pairs.i1.testmatch.counts

array([15,  6, 21, ...,  0,  1,  3])

In [154]:
muon_pairs.i1.pt.counts

array([15,  6, 21, ...,  0,  1,  3])

In [159]:
muon_pairs[muon_pairs.i0.testmatch>0]

<JaggedArrayMethods [[<tuple 0> <tuple 1> <tuple 2> ... <tuple 6> <tuple 7> <tuple 8>] [<tuple 15> <tuple 16> <tuple 17> <tuple 18> <tuple 19>] [<tuple 27> <tuple 28> <tuple 29> <tuple 30> <tuple 31>] ... [] [<tuple 251457>] [<tuple 251458> <tuple 251459> <tuple 251460>]] at 0x7f21379fea60>

In [160]:
muon_pairs[muon_pairs.i0.pt>30]

<JaggedArrayMethods [[] [] [<tuple 27> <tuple 28> <tuple 29> <tuple 30> <tuple 31>] ... [] [<tuple 251457>] []] at 0x7f2136ec34c0>